# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cesco/pd/intelligentSportMonitoring

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cesco/pd/intelligentSportMonitoring

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cesco/pd/intelligentSportMonitoring/CMakeFiles /home/cesco/pd/intelligentSportMonitoring/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cesco/pd/intelligentSportMonitoring/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aux

# Build rule for target.
aux: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aux
.PHONY : aux

# fast build rule for target.
aux/fast:
	$(MAKE) -f CMakeFiles/aux.dir/build.make CMakeFiles/aux.dir/build
.PHONY : aux/fast

#=============================================================================
# Target rules for targets named playerdetect

# Build rule for target.
playerdetect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 playerdetect
.PHONY : playerdetect

# fast build rule for target.
playerdetect/fast:
	$(MAKE) -f CMakeFiles/playerdetect.dir/build.make CMakeFiles/playerdetect.dir/build
.PHONY : playerdetect/fast

aux.o: aux.cpp.o

.PHONY : aux.o

# target to build an object file
aux.cpp.o:
	$(MAKE) -f CMakeFiles/aux.dir/build.make CMakeFiles/aux.dir/aux.cpp.o
.PHONY : aux.cpp.o

aux.i: aux.cpp.i

.PHONY : aux.i

# target to preprocess a source file
aux.cpp.i:
	$(MAKE) -f CMakeFiles/aux.dir/build.make CMakeFiles/aux.dir/aux.cpp.i
.PHONY : aux.cpp.i

aux.s: aux.cpp.s

.PHONY : aux.s

# target to generate assembly for a file
aux.cpp.s:
	$(MAKE) -f CMakeFiles/aux.dir/build.make CMakeFiles/aux.dir/aux.cpp.s
.PHONY : aux.cpp.s

playerdetector.o: playerdetector.cpp.o

.PHONY : playerdetector.o

# target to build an object file
playerdetector.cpp.o:
	$(MAKE) -f CMakeFiles/playerdetect.dir/build.make CMakeFiles/playerdetect.dir/playerdetector.cpp.o
.PHONY : playerdetector.cpp.o

playerdetector.i: playerdetector.cpp.i

.PHONY : playerdetector.i

# target to preprocess a source file
playerdetector.cpp.i:
	$(MAKE) -f CMakeFiles/playerdetect.dir/build.make CMakeFiles/playerdetect.dir/playerdetector.cpp.i
.PHONY : playerdetector.cpp.i

playerdetector.s: playerdetector.cpp.s

.PHONY : playerdetector.s

# target to generate assembly for a file
playerdetector.cpp.s:
	$(MAKE) -f CMakeFiles/playerdetect.dir/build.make CMakeFiles/playerdetect.dir/playerdetector.cpp.s
.PHONY : playerdetector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... aux"
	@echo "... playerdetect"
	@echo "... aux.o"
	@echo "... aux.i"
	@echo "... aux.s"
	@echo "... playerdetector.o"
	@echo "... playerdetector.i"
	@echo "... playerdetector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

